### ISSUE TITLE
Restart webserver calls apache instead of nginx

### ISSUE THREAD

**Issue by ivanjaros** [geerlingguy/ansible-role-php#101]
Hi, I am setting up a webserver on Ubuntu with the following roles: geerlingguy.git, geerlingguy.nginx, geerlingguy.php, geerlingguy.composer and geerlingguy.drush and at the last step I get "running handler geerlingguy.php restart webserver" and for some reason it tries to restart apache2 which I don't have(as you can see, I'm using nginx role). In my playbook I have the php_webserver_daemon set to nginx but it looks like it has no effect in this case. I have tried to manually change the variable __php_webserver_daemon in vars/Debian.yml and set exact value in handlers/main.yml but it had no effect.

This is my setup:

```
---
- name: Configure webserver instance.
  hosts: webservers
  remote_user: root
  roles:
    - {
        role: geerlingguy.git,
        git_version: "2.7.4",
        git_packages: [git]
      }
    - {
        role: geerlingguy.nginx,
        nginx_remove_default_vhost: true
      }
    - {
        role: geerlingguy.php,
        php_webserver_daemon: "nginx",
        php_enable_php_fpm: true,
        php_opcache_enabled_in_ini: true,
        php_apc_enabled_in_ini: true
      }
    - {
        role: geerlingguy.composer
      }
    - {
         role: geerlingguy.drush
       }
```

**Comment by geerlingguy** [comment]
Can you try setting `php_webserver_daemon` up a level in your playbook, like:

```yaml
- name: Configure webserver instance.
  hosts: webservers
  remote_user: root

  vars:
    php_webserver_daemon: "nginx"

  roles:
    ...
```

That way if another role is causing the restart, it will have the proper variable throughout.

**Comment by ivanjaros** [comment]
Yep, that worked.
