### ISSUE TITLE
503 Service unavailable traced to php5-fpm segfault errors

### ISSUE THREAD

**Issue by sidneygijzen** [geerlingguy/ansible-role-php#102]
I was setting up a DrupalVM box, and somehow I couldn't load any of my Drupal sites. I kept getting 503 Service unavailable errors.

I checked the php5-fpm log, where I saw this error
`[proxy_fcgi:error] [pid 843:tid 140246159181568] [client xxx.xxx.x.xx:53:53474] AH01067: Failed to read FastCGI header`

I tracked it back to syslog, where this one was displayed
`php5-fpm[955]: segfault at 7ffdff504f48 ip 00007f9eb0ec755a sp 00007ffdff504f40 error 6 in libpcre.so.3.13.1[7f9eb0eb4000+3d000]`

I solved the error by setting `pcre.recursion_limit=1000` in `/etc/php5/fpm/php.ini` and restarting the php5-fpm service (source: [StackOverflow answer](http://stackoverflow.com/a/31840525)).

Is this something you would like to add to the used `php.ini` in this role? And if so, I was wondering if you want to make it configurable?

**Comment by geerlingguy** [comment]
I'm assuming you'd like the `pcre.recursion_limit` to be configurable?

**Comment by sidneygijzen** [comment]
Yeah, I think that would be the most elegant solution. If you're ok with that, I can do a PR.

**Comment by geerlingguy** [comment]
Yep!
