### ISSUE TITLE
Travis source build test times out after 10 minutes

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#105]
It looks like I can add `travis_wait 30` before the docker step that runs the playbook inside the container, and that might fix it. See latest build failure: https://travis-ci.org/geerlingguy/ansible-role-php/jobs/121786496

**Comment by 030** [comment]
did this solve the issue? I do not see the travis_wait in the .travis file anymore

**Comment by geerlingguy** [comment]
I haven't had the issue anymore since the tasks that take a lot of time seem to complete in < 10 min now.
