### ISSUE TITLE
CLI Timezone not effected by php_date_timezone

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/ansible-role-php#108]
I've set ```php_date_timezone: "Europe/London"``` and confirmed this exists in ```/etc/php5/php.ini``` however when running Drupal console I get:

```The configuration date.timezone was missing and overwritten with America/Tijuana.```

Configuring date.timezone in ```/etc/php5/cli/php.ini``` fixes this.

I guess this is a bit awkward since you don't really want the main php.ini to effect some of the cli properties, is it possible to create a new cli php.ini and then include it as part of the main cli php.ini?

**Comment by geerlingguy** [comment]
Hmm... I currently don't touch the cli config at all with this role, as the role's focus is more on other aspects of PHP config, and the CLI options are often highly individualized for those who spend time running PHP via CLI. I'm inclined to recommend managing that particular ini file separately.

**Comment by mikebell** [comment]
That's fine, I was wondering if that might be the case. Closing.
