### ISSUE TITLE
manage php-fpm pools

### ISSUE THREAD

**Issue by drupaladmin** [geerlingguy/ansible-role-php#111]
Hi!

What do you think about ability to manage php-fpm pools in this role?

**Comment by geerlingguy** [comment]
I don't think I want to add that specific capability to this role; I'd rather leave any specialized pool config to another role or playbook. Typically, the default/single pool is adequate for most use cases, and I think adding that config to this role wouldn't be worth the extra effort required to maintain it (whereas this role's primary focus is getting PHP installed and the basics configured).

**Comment by jamieburchell** [comment]
It would be good to be able to manage the php-fpm pools manually, but still enable php-fpm in this playbook so the service is enabled. Unfortunately, if you enable it, you are forced to use a default "www.conf" pool. Having one pool Ansible managed and the others manual isn't ideal. If you prevent the www.conf pool from being written to, the play fails.
