### ISSUE TITLE
Release 2.0.3 won't install

### ISSUE THREAD

**Issue by siliconmeadow** [geerlingguy/ansible-role-php#114]
Hi,

When I do a: `sudo ansible-galaxy install -r provisioning/requirements.yml --force`, I get the following message:
```
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
```
I have downgraded to 2.0.2 and it get no errors.

I'm happy to supply more details or dig further if you need me to.

Cheers,

Richard

**Comment by geerlingguy** [comment]
What version of Ansible are you currently running? If you're on 1.9.x, please see if upgrade to 2.0.x fixes the issue (see this upstream bug): https://github.com/ansible/galaxy-issues/issues/134

**Comment by siliconmeadow** [comment]
You're right. I now see that it was reported previously. Duplicates #110 .

Thanks!
