### ISSUE TITLE
Add support for PHP 7

### ISSUE THREAD

**Issue by ivanjaros** [geerlingguy/ansible-role-php#115]
PHP 7 is out for a while so it would be nice to be able to set php_version: 7 and get it instead of 5.

**Comment by geerlingguy** [comment]
PHP 7 is fully supported by this role, and only requires you to either:

  1. Make sure your OS's default packages (e.g. Ubuntu 16.04) provide PHP 7.
  2. Install a PPA/repo for apt/yum/dnf that provides PHP 7 (e.g. DotDeb, Ondrej, Remi) before running this role.
  3. Use source install and set a PHP version to install (e.g. 7.0.5).

For an example of 2, see how Drupal VM does it: http://docs.drupalvm.com/en/latest/other/php-7/

For an example of 3, see how Drupal Pi does it: https://github.com/geerlingguy/drupal-pi/blob/master/vars/source-install.yml

**Comment by jcroll** [comment]
For example 2 you can see the Debian example here (as @geerlingguy your link is outdated): https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L32
