### ISSUE TITLE
php.ini display_startup_error default

### ISSUE THREAD

**Issue by jmooo** [geerlingguy/ansible-role-php#116]
Is there a reason `php_display_startup_errors: "On"` is the default value? At least in the CentOS 7 php.ini this value defaults to Off and strongly urges you to leave it off in a production environment

> ; The display of errors which occur during PHP's startup sequence are handled
> ; separately from display_errors. PHP's default behavior is to suppress those
> ; errors from clients. Turning the display of startup errors on can be useful in
> ; debugging configuration problems. But, it's strongly recommended that you
> ; leave this setting off on production servers.
> ; Default Value: Off
> ; Development Value: On
> ; Production Value: Off
> ; http://php.net/display-startup-errors
> display_startup_errors = Off

**Comment by FinBoWa** [comment]
The defaults should set it to off https://github.com/geerlingguy/ansible-role-php/blob/2.0.3/defaults/main.yml#L68

Only the README says the default is ON what seems to be a documentation issue.
