### ISSUE TITLE
failure on checking php version

### ISSUE THREAD

**Issue by fxer** [geerlingguy/ansible-role-php#117]
On CentOS 7 I have the current php-fpm package installed, which does not require the 'php' package to be installed. When running this role I get a failure on the task "Check the installed version of PHP" because it is trying to run php directly from the cli, which is not installed because it is unnecessary.

**Comment by geerlingguy** [comment]
This will fixed by dropping support for PHP < 5.5, which has already happened in master and will be released soon!
