### ISSUE TITLE
make fpm user configurable

### ISSUE THREAD

**Issue by quinn** [geerlingguy/ansible-role-php#119]
Would this be a welcome contribution?

**Comment by geerlingguy** [comment]
What would be the use case? I haven't seen someone want to change it from the default on systems I've used, but if there's a compelling reason, I could do it.

**Comment by FinBoWa** [comment]
@geerlingguy We always create fpm pools per user if the server is used for many sites for different users or we want to isolate the processes. 

Thought we use this role and in separate tasks copy the different pools template files to the right folder and set the correct permissions for the wdsl cache folders and what nots. 

So only way to make this more usable would be to allow to create multiple pools. If it's just allowing to change the name, then I don't personally see the point.

**Comment by quinn** [comment]
@geerlingguy I ended up reconfiguring my script to use the default user. Seems more sensible that way.

**Comment by geerlingguy** [comment]
Note that I also just merged in https://github.com/geerlingguy/ansible-role-php/pull/128, which allows the group/user to be configured.

**Comment by quinn** [comment]
@geerlingguy cool, thank you!
