### ISSUE TITLE
PHP-FPM fails on Centos because of wrong configuration.

### ISSUE THREAD

**Issue by valdars** [geerlingguy/ansible-role-php#120]
PHP-FPM config file www.conf sets user and group for apache to "www-data" but in Centos Apache user and group are "apache" instead. This causes PHP-FPM start to fail, because it tries to get UUID of user that does not exist.

**Comment by geerlingguy** [comment]
See note: https://github.com/geerlingguy/ansible-role-php/pull/128/files#r63909372
