### ISSUE TITLE
PHP 5.6 support for Debian/Ubuntu

### ISSUE THREAD

**Issue by acie** [geerlingguy/ansible-role-php#121]
Is there a support for installing PHP5.6 for debian/ubuntu based instances? It only install PHP5.5 version unlike CentOS/Redhat based there is an option to enable repo for PHP5.6 supports.

Additionally, I wasn't able to enabled OpCache even though I have configured the settings to true and 1 for these configurations respectively:
php_opcache_enabled_in_ini: true
php_opcache_enable: "1"
php_opcache_enable_cli: "1"

Thanks.

**Comment by geerlingguy** [comment]
@acie for the best point of reference, check out how Drupal VM installs different versions of PHP using this role:

https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L22-L32

**Comment by aistis-** [comment]
And what about CentOS and RedHat?

**Comment by geerlingguy** [comment]
@aistis- it's supported—and waaaaay easier than debian-based distributions, because all you need to do is change `php_version: 5.6` in your config file.

See: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-redhat.yml#L18-L20

**Comment by aistis-** [comment]
Thanks, it worked :+1:
