### ISSUE TITLE
Ensure PHP packages are installed failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by smalatrait** [geerlingguy/ansible-role-php#129]
Ubuntu 14.04, Since the change from php5 to php7, when using ansible-role-drupal, the dependencies ansible-role-php fail because php7 isn't on official 14.04 repository.

In tasks/setup-Debian.yml, adding the repository before those task are called fix the issue:

- name: Add php7 Repo for Ubuntu 14.04.
  apt_repository: repo='ppa:ondrej/php'

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver 

Did you notice the issue ? have you any idea how to fix this in a better way please ?

Forgot to add: Thanks for the good work @geerlingguy !

**Comment by geerlingguy** [comment]
@smalatrait - Sorry about that! And yes, your solution should work fine, and is great if you're okay with using PHP 7 (which is optimal for Drupal 8).

If you want to continue using PHP 5.6, then you need to make these changes: http://docs.drupalvm.com/en/latest/other/php-56/

**Comment by geerlingguy** [comment]
(See also: https://github.com/geerlingguy/drupal-vm/pull/714)

**Comment by thuannvn** [comment]
Thanks geerlingguy for good work, also smalatrait for fix issue on Ubuntu 14.04, this solve my issues
