### ISSUE TITLE
CLI apc/apcu extension warnings.

### ISSUE THREAD

**Issue by joestewart** [geerlingguy/ansible-role-php#130]
Following up after #125.

Using version 3.0.4 and DrupalVM with geerlingguy/1404.

If php_apc_enabled_in_ini: false we see this warning since apcu extension is not loaded.

```PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/apc.so' - /usr/lib/php/20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0```

If php_apc_enabled_in_ini: true we see this warning since apc extension is also loaded in 20-apcu_bc.ini.
```PHP Warning:  Module 'apc' already loaded in Unknown on line 0```

It appears php-apcu-bc is automatically installed.  Not sure the best solution for a PR.

**Comment by joestewart** [comment]
It appears for Ubuntu 14.04 and 16.04 we should remove loading apc.so from the template.  No idea on Redhat based OS.
```diff --git a/templates/apc.ini.j2 b/templates/apc.ini.j2
index 468c27a..a012a43 100644
--- a/templates/apc.ini.j2
+++ b/templates/apc.ini.j2
@@ -1,6 +1,5 @@
 {% if php_apc_enabled_in_ini %}
 extension=apcu.so
-extension=apc.so
 {% endif %}
 apc.shm_size={{ php_apc_shm_size }}
 apc.enable_cli={{ php_apc_enable_cli }}```

**Comment by rockholla** [comment]
I just noticed this yesterday as well.  I'm actually going to work on a fix today and submit a pull request from my fork.  And per RedHat, there are related issues on CentOS/RedHat as well.  I think the best solution is to search for default apc conf files that already exist in the conf path and just modify those according to the role variables set.

**Comment by JorisVanEijden** [comment]
I was using APC as opcache on a number of CentOS 6 servers. After updating this role they started throwing: `PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/apcu.so' - /usr/lib64/php/modules/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0`
So for me I had to do the reverse and remove the `extension=apcu.so` line..

**Comment by joestewart** [comment]
I added some tests in #132 that illustrate this.  But don't think it tests CentOS 6.  thanks.

**Comment by JorisVanEijden** [comment]
Looks like I need to roll back and stick to version 2.0.3 of this role.
I have too many drupal 6 and other php 5.3 servers to support..

**Comment by rockholla** [comment]
@JorisVanEijden feel free to use the branch I have awaiting to be merged back in to master here: https://github.com/rockholla/ansible-role-php/tree/apc-opcache-config-tweaking.  I've been using it on a few of my projects and may actually put in some other work and publish separately to Galaxy soon.  I know geerlingguy has a lot going on.

**Comment by geerlingguy** [comment]
This should hopefully be fixed by the change @rockholla added, present very soon (once I tag it) in `3.2.0`.

**Comment by JorisVanEijden** [comment]
@rockholla doesn't look like your work allows me to use APC as an opcache. Also @geerlingguy has indicated that PHP 5.3 support of this role has ended with version 3.0.0
That's okay. But I can't have two roles, so I'll stick to using 2.0.3 for all our systems.
As a Drupal 6 LTS provider we're stuck with Drupal 6 (and clients unwilling/unable to upgrade anything) for a while yet.

**Comment by rockholla** [comment]
@JorisVanEijden just testing with [about the simplest playbook possible](https://gist.github.com/rockholla/2b419dc846f69ffb610fead59daea3b8) I can toggle APC on and off in the PHP config by changing the value of `php_enable_apc`.  Seems to be working OK in this case.  I haven't checked on what might be happening with 5.x and I will check that out as soon as I can, but maybe you're not seeing it turned out when checking via `php -i` because `php_apc_enable_cli` is not set to true/yes?  Just one thought.

Something else: could you update your PHP version beyond 5.3?  Drupal 6 I believe supports all 5.x versions.  Not that it's necessarily relevant to your issues here, but worth mentioning.

**Comment by JorisVanEijden** [comment]
@rockholla it works fine for APC**u** (APC without opcaching) but not for APC (with opcaching)
Try it on CentOS 6  with php-pecl-apc in stead of php-pecl-apcu
And no, sadly Drupal 6 doesn't work properly on PHP 5.4 or higher.

**Comment by rockholla** [comment]
@JorisVanEijden  I see, I read your previous message a little too quickly and missed the "as an opcache".  Yeah, I'm guessing this is problematic for pre php 5.5 only, but I'll continue to check in to this for >= 5.5 when I get a chance.

And I also see now that 5.x is supported by Drupal 6, but they note that > 5.3.x could produce errors for core modules or themes, which I'm guessing is what you're running up against.  Sorry you're having to deal with situations where upgrading is not an option.
