### ISSUE TITLE
How to set php version ?

### ISSUE THREAD

**Issue by girod** [geerlingguy/ansible-role-php#134]
I don't see where you set var to choose the php version.
I used the role like this, and the php version installed by default is 5.4 (on centos)

Thks

**Comment by acie** [comment]
I think you need to include in your playbook
vars:
    php_version: 5.6
    php_enablerepo: "remi,remi-php56"

This depends on your PHP version.

Thanks.

**Comment by geerlingguy** [comment]
There are also different ways to set different PHP versions on other platforms too—for some good examples, see how Drupal VM does it:

  - Debian: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L19-L33
  - RedHat: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-redhat.yml#L13-L23

By default, the role will use whatever packages are available in the system repos, or in CentOS' case, what's set with `php_enablerepo`. And you can always fall back to source install if you need a specific/exact version :)

**Comment by jasperf** [comment]
These links to Debian should now be https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-Debian.yml I believe. Still not quite sure how I should call a repo for Debian and then PHP 7.1 though. Or if I need to recall a repo at all.

**Comment by geerlingguy** [comment]
@jasperf - see https://github.com/geerlingguy/drupal-vm/issues/1377 — I'm planning on extracting the functionality to a new `geerlingguy.php_versions` role on Ansible Galaxy.

**Comment by geerlingguy** [comment]
@jasperf yep, that's exactly what you'd do—and it works on Debian, CentOS, Ubuntu, etc.
