### ISSUE TITLE
Unable to load apc.so as a result of role switching to apcu

### ISSUE THREAD

**Issue by pporada-gl** [geerlingguy/ansible-role-php#136]
When using geerlingguy.php, `templates/apc.ini.j2` contains the following lines
```
extension=apcu.so
extension=apc.so
apc.shm_size={{ php_apc_shm_size }}
apc.enable_cli={{ php_apc_enable_cli }}
apc.rfc1867=1
```

As a result of the template containing `extension=apc.so`, pear fails because it cannot find `apc.so`
```
==> default: TASK [geerlingguy.php-pear : Discover required PEAR channels.] *****************
==> default: failed: [localhost] (item=pear.symfony.com) => {"changed": false, "cmd": ["pear", "channel-discover", "pear.symfony.com"], "delta": "0:00:00.034408", "end": "2016-06-10 19:31:34.796956", "failed": true, "failed_when_result": true, "item": "pear.symfony.com", "rc": 1, "start": "2016-06-10 19:31:34.762548", "stderr": "PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/apc.so' - /usr/lib64/php/modules/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0", "stdout": "Channel \"pear.symfony.com\" is already initialized", "stdout_lines": ["Channel \"pear.symfony.com\" is already initialized"], "warnings": []}
```

I am on CentOS7 and don't have APC, just APCu.
```
[root@localhost ~]# rpm -qa | grep apc
php-pecl-apcu-4.0.11-1.el7.remi.5.5.x86_64

[root@localhost ~]# ls -al /usr/lib64/php/modules/apc*
-rwxr-xr-x. 1 root root 106528 Apr 20 11:55 /usr/lib64/php/modules/apcu.so
```

The way I fixed this was to alter the template to be.
```
extension=apcu.so
apc.shm_size={{ php_apc_shm_size }}
apc.enable_cli={{ php_apc_enable_cli }}
apc.rfc1867=1
```

What I am not sure of is if me submitting this change and it being approved will break anything downstream.

**Comment by geerlingguy** [comment]
Yeah, looks like this was introduced by a recent change in this commit: https://github.com/geerlingguy/ansible-role-php/commit/b9f0a6172000fb834a95fb30f5c46cafe03f4331

I'm reverting part of the change (removing `apc.so`) because with PHP 5.5+, `apc.so` isn't really supported—only APCu. So hopefully this will fix things! (I just ran into the same issue when doing a staging server build tonight).
