### ISSUE TITLE
find module is not ansible 1.9 compatible

### ISSUE THREAD

**Issue by juban** [geerlingguy/ansible-role-php#137]
Latest update broke the 1.9 compatibility.
Running this role throw this error:
`ERROR: find is not a legal parameter in an Ansible task or handler`

**Comment by geerlingguy** [comment]
Ah, true... I'll need to update https://github.com/geerlingguy/ansible-role-php/blob/master/meta/main.yml#L9 to default to Ansible 2.x. Most of my roles are 2.0+ at this point, as it's getting harder to live without all the awesome new modules and conveniences in 2.x.
