### ISSUE TITLE
Unable to download - missing role versions

### ISSUE THREAD

**Issue by JeromeGill** [geerlingguy/ansible-role-php#141]
Not 100% if this is a tagging issue or what. Looks like it won't download due to a null role_versions

- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 957, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 951, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()

If a version needs to be explicit, perhaps a default to the latest version would be helpful

**Comment by JeromeGill** [comment]
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50 This is 404'ing which may be the issue

**Comment by joestewart** [comment]
Which version of ansible are you using?  A Galaxy upgrade broke the 1.9.x series and required a recent release or upgrade to 2.x  See #110

**Comment by geerlingguy** [comment]
@JeromeGill - Yeah, that's a bug in Ansible pre-1.9.something. Please make sure you're running the latest version of Ansible (2.1.0 as of this writing). Check version with `ansible --version`.

**Comment by JeromeGill** [comment]
Thanks, that was it indeed. Must have missed the memo!
