### ISSUE TITLE
www.conf not overwritten

### ISSUE THREAD

**Issue by seeafish** [geerlingguy/ansible-role-php#146]
Hi there.
I was a bit puzzled when troubleshooting why my www.conf wasn't the same as the templated file in this role.
I found this line that explains this behaviour: https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/configure-fpm.yml#L43

My argument here is that you would expect any configuration management to manage the configuration files, so I think it would be safe to assume that files will and should be overwritten by default.
In this case, my default CentOS7 installed php-fpm drops in a bog standard www.conf file, which means that this role can no longer manage that until I remove it manually or via some other ansible play.

Any particular reason why we're setting `force: no` in this case?

Thanks.

**Comment by icamys** [comment]
I have a related question. Now I am using ansible galaxy to download and install roles. Those roles are not included in index of the VCS (in my case it's git). I want to override `www.conf` without modifying any files in role. Is it possible?

**Comment by FinBoWa** [comment]
@icamys that's basically ansible issue. I'v keep holding my breath for a feature on ansible that would allow overriding the role includes "ad hoc" without the role developer need to do special things to "allow" a inclusion. 

At the moment you have these options:

1. use lineinfile or something else to change values to suit your need after the role has done its bits
2. copy the roles template file > amend it and use the tempalte methods to copy it to the remote AFTER the role; you should be able to use all the variables (at least on 1.9)
3. fork the project and use require.yml to change the repo where the role should be downloaded from; ansible will use the native name of the role still.

**Comment by noplanman** [comment]
@geerlingguy It would be really helpful if we could override all the included templates completely, something like https://github.com/geerlingguy/ansible-role-nginx/pull/99
