### ISSUE TITLE
Ability to compile some PHP modules when using system packages for everything else

### ISSUE THREAD

**Issue by TanmayaA** [geerlingguy/ansible-role-php#152]
While PHP system packages cover most uses, at times we need ability to compile a few PHP modules from source when there is no system package available.

**Comment by geerlingguy** [comment]
This is a bit more of an advanced use case, that I would rather not cover with this particular role—what I normally do is have a secondary role that runs after this one, which compiles the module and configures it with a separate config file in conf.d.

For example:

  - https://github.com/geerlingguy/ansible-role-php-xhprof
  - https://github.com/geerlingguy/ansible-role-php-xdebug
