### ISSUE TITLE
Unable to install role/s

### ISSUE THREAD

**Issue by icarlosmendez** [geerlingguy/ansible-role-php#167]
Hello, 
It appears that the path to the roles tarball file is not correct. Did I miss something somewhere?

`MacBook-Pro:vagrant_ansible_test hive$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.4.2.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.`

This same issue is present on other roles as well. Interested in your thoughts.
Thanks,
Carlos

**Comment by geerlingguy** [comment]
@icarlosmendez - I'm able to access that URL from my home and two other VPSes I just tried. Could you be on a network that restricts GitHub download access? Or it could've also been a temporary GitHub issue... can you test again?

**Comment by icarlosmendez** [comment]
@geerlingguy - Hey Jeff, I didn't realize you had replied so many days ago otherwise I would have written back sooner. I have attempted to install the role again using Ansible's cli without success. I was able to download the tarball at the URL listed though. 

Is there a technique for installing the role manually once I have the tarball? I'm thinking that since it would normally be installed by Ansible that just expanding the tarball might not give the desired results.

**Comment by geerlingguy** [comment]
Ansible generally sticks roles inside `/etc/ansible/roles`, so if that directory doesn't exist, create it using `sudo` then use `sudo` to `wget` or copy the downloaded role into place (that's basically all `ansible-galaxy` does).

**Comment by icarlosmendez** [comment]
I appreciate your assistance with this. I have one final question regarding this 'manual setup' though. 
Via some sample code I came up with these roles declarations.
roles:
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php-mysql }

Should the directory for each individual role be named geerlingguy.xxx in order for the role to be recognized? Because expanding the tarball resulted in a 'root' directory named 'ansible-role-php-3.4.2'.

**Comment by geerlingguy** [comment]
Yes, if you download them, rename the dirs to just `geerlingguy.[rolename]`
