### ISSUE TITLE
Use proper configuration paths in Debian/Ubuntu

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#17]
Because of Debian/Ubuntu's handling of PHP/Apache configuration paths, both the `php_conf_path` and `php_extension_conf_path` are incorrect if you're using PHP as php-fpm or with a different webserver, like Nginx... Therefore, we need to be able to put the configuration files in the correct locations (e.g. `/etc/php5` and `/etc/php5/conf.d`, then only symlink them into the apache2-specific folders if PHP is being run with Apache.

**Comment by geerlingguy** [comment]
This should be working correctly now; it's in the 1.4.0 release.

**Comment by LewisW** [comment]
I don't think this actually symlinks the APC conf file in to the relevant SAPI conf.d. Subsequently I think the Xdebug role has failed (that's how I noticed). The easy fix is to change the php_extension_conf_path to the SAPI specific conf.d folder, but the "Debian way" is to symlink them (which would mean updating this role and any related ones)

**Comment by andreasradloff** [comment]
Hi! I can confirm xdebug not being included in apache, I had to duplicate the cli symlink-block in the xdebug task file, but I guess I don't have apc either.  Didn't help putting this in my config.yml (using your Drupal VM):
php_extension_conf_path: "/etc/php5/apache2/conf.d"
New to Ansible so I don't know why it didnt help.

**Comment by geerlingguy** [comment]
FYI after starting to use Debian (7) and Ubuntu (14.04) a bit more for some of my infrastructure, I've _really_ come to hate the 'debian way' — infrastructure-as-code doesn't really require the idea of a 'sites-available' / 'sites-enabled' or a bunch of symlinked config directories. Just throw the configuration files where they need to be, and you're done with it ;-)

But there are still a couple rough areas here, since Debian-like distros do seem to have separate conf.d folders for every kind of PHP-related webserver under the sun. While I can't account for them all, I'd like to at least make sure this role works correctly with:

  - Apache (both mpm-worker and prefork)
  - Nginx
  - PHP FPM
  - PHP CLI

I think I have these mostly working—see https://github.com/geerlingguy/ansible-role-php/issues/26.

@andreasradloff - That problem might need to be addressed in the xdebug role separately.
