### ISSUE TITLE
Add Ondrej PPA on config

### ISSUE THREAD

**Issue by dqlopez** [geerlingguy/ansible-role-php#184]
I always get `"No package matching 'php' is available"` while provisioning an Ubuntu Server 14.04.5 LTS. I can't see any option in the README on how to add PPA for PHP (Ubuntu) (eg. **Ondrej**).

```
php_version: "7.1"
php_packages_state: "latest"
php_webserver_daemon: "nginx"
php_fpm_pool_user: "nginx"
php_fpm_pool_group: "nginx"
php_enable_php_fpm: true
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-fpm
  - php-fpm-nginx
  - php-pgsql
```

**Comment by geerlingguy** [comment]
See example implementation in Drupal VM: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L32-L35

**Comment by dqlopez** [comment]
Thanks, I did as what based on you referred. It works fine now, however I get this non-blocker issue during provision:

```
TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ***
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service php7.0-fpm: cannot enable"}
```
I'm confuse why it still sees daemon as `php7.0-fpm` which should be `php7.1-fpm` already.

**Comment by geerlingguy** [comment]
You would also need to change any of the other `php7.x-*` variables... basically any variable that has `7.0` anywhere in it needs to be overridden with the equivalent variable but with the changed version:

https://github.com/geerlingguy/ansible-role-php/blob/master/vars/Debian.yml

**Comment by geerlingguy** [comment]
(Noting also that you should set the variables using the non-prefixed variable name (e.g. drop the `__` from each variable as you add them to your playbook).

**Comment by dqlopez** [comment]
I already did change the variable name, there it seems that I miss the `php_fpm_daemon` variable.
