### ISSUE TITLE
Official Nginx fails to restart

### ISSUE THREAD

**Issue by noplanman** [geerlingguy/ansible-role-php#190]
In my setup, I add the official stable Nginx repo from here:
https://nginx.org/en/linux_packages.html#stable

Using the `geerlingguy.nginx` role to install it works perfectly.

But when I use this PHP role, ansible dies when trying to [restart the webserver](https://github.com/geerlingguy/ansible-role-php/blob/3.4.4/handlers/main.yml#L2).

I get the following error:
`fatal: [0.0.0.0]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service nginx: Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.\n"}`

When I SSH in to see what's up, I can see that the problem is this:
```
vagrant@www:~$ sudo service nginx status
● nginx.service - LSB: Stop/start nginx
   Loaded: loaded (/etc/init.d/nginx)
   Active: failed (Result: exit-code) since Mon 2017-04-24 11:39:52 GMT; 9min ago
  Process: 20634 ExecStop=/etc/init.d/nginx stop (code=exited, status=0/SUCCESS)
  Process: 20606 ExecReload=/etc/init.d/nginx reload (code=exited, status=0/SUCCESS)
  Process: 20640 ExecStart=/etc/init.d/nginx start (code=exited, status=1/FAILURE)

Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Apr 24 11:39:52 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:52 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Apr 24 11:39:52 www systemd[1]: nginx.service: control process exited, code=exited status=1
Apr 24 11:39:52 www systemd[1]: Failed to start LSB: Stop/start nginx.
Apr 24 11:39:52 www systemd[1]: Unit nginx.service entered failed state.
Apr 24 11:39:52 www nginx[20640]: nginx: [emerg] still could not bind()
```

I can't seem to stop the service either, so it seems the process running isn't connected to the service runner.
When I kill the running nginx process and replay the provision, it goes through smoothly.
Also, when I do the installations by hand on the vagrant machine, the restart works without any problems.

Not really sure why the service fails to restart properly, any ideas?

**Comment by geerlingguy** [comment]
```
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:51 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Apr 24 11:39:52 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 24 11:39:52 www nginx[20640]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
```

Is nginx already running on the server, and it's using `80`/`443`, or could there be an instance of Apache running on those ports?

Also, what OS are you running? I haven't had issues with CentOS 7 or Ubuntu 16.04, though I haven't tested as much on some other systemd-using OSes.

**Comment by noplanman** [comment]
Using your Nginx role, after the installation of Nginx, it [gets started](https://github.com/geerlingguy/ansible-role-nginx/blob/2.2.0/tasks/main.yml#L41). So yes, there is an instance of Nginx running.

There is no Apache installed, only Nginx. If I kill just the running Nginx process and rerun the playbook all is good. So it seems as if the running process isn't being controlled by the Nginx `service`. Even a `service nginx stop` on the machine doesn't help, I need to kill it.

I'm on Debian 8.7 (Jessie).

Also, on a side note, are there 3 entries in the error log because Ansible tries 3 times?

**Comment by johnyserpa** [comment]
@noplanman this is also happening to me. Any idea why this happens?

**Comment by noplanman** [comment]
@johnyserpa Unfortunately not.

Haven't needed this role for an initial setup since I posted this issue, so I don't know if it's still the case for Debian based systems. As for CentOS, I never tried that.

So you're having the exact same issue then?

Maybe @geerlingguy has found something out?

**Comment by geerlingguy** [comment]
I still haven't had issues testing with Debian 9 or Ubuntu 16.04, which I use all over the place, but I haven't spent as much time testing on Debian 8 (besides the automated role tests that are run weekly).
