### ISSUE TITLE
Add automated tests for Debian 8, fix systemd not enabling

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#191]
I've been hitting an issue with the `php7.1-fpm` service not showing as enabled via `systemctl status` over in Drupal VM (when building a Docker container for the VM)—see https://github.com/geerlingguy/drupal-vm/issues/1366, the first issue in that list.

Then I realized I don't have any automated test coverage in _this_ repo, and that's probably why there are little broken things like this! I need to add automated test coverage, fixing any issues that are exhibited by said tests.

**Comment by geerlingguy** [comment]
Funny enough... tests are passing locally without me changing anything, even though when I check inside the container:

```
root@7da2a033d088:/# systemctl status php7.0-fpm
● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; disabled)
   Active: inactive (dead)
     Docs: man:php-fpm7.0(8)

root@7da2a033d088:/# php -v
Cannot load Zend OPcache - it was already loaded
PHP 7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9 (cli) (built: May 13 2017 14:03:21) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1+0~20170513113901.30+jessie~1.gbpff7ec9, Copyright (c) 1999-2017, by Zend Technologies
```

So I should probably add in a test to verify the service is _actually_ enabled. Or at least file a bug (or find an existing bug) with Ansible's `service` module on Debian 8 systemd...

**Comment by geerlingguy** [comment]
Yay, I got the Debian 8 test to fail, while it's working on other systemd distros :)

**Comment by oxyc** [comment]
Any chance it's this one https://github.com/ansible/ansible-modules-core/issues/3764#issuecomment-284331673

**Comment by oxyc** [comment]
Seems that was the bug, https://travis-ci.org/geerlingguy/ansible-role-php/jobs/232887274#L756

Can't really go with `use: service` though as it requires Ansible 2.2

**Comment by geerlingguy** [comment]
@oxyc - D'oh! Well, another option is to:

  - Bump the role to 2.2 (many of my roles are there already :)
  - Add a `when` on the existing `service` task and set it to 'not debian / not jessie' (something like that)
  - Add a second `service` task with a link to that upstream issue (`# See [url]`) and the `use: service`.

**Comment by geerlingguy** [comment]
(If you want to make those changes in your PR I'll merge it and close my original one)

**Comment by oxyc** [comment]
I was just debugging a bit while waiting for a provision to finish at work (production drupal vm 🎉) :) Feel free to fix it, otherwise I can take a look later after I finish work.
