### ISSUE TITLE
PHP 7.1 "503 service unavailable"

### ISSUE THREAD

**Issue by WiseUA** [geerlingguy/ansible-role-php#192]
For my project I use PHP 7.1 and found an error in this role. Version 7.1 does not work until in the file:
`roles/geerlingguy.php/vars/Debian.yml` does not changed the variable `__php_fpm_conf_path` on `/etc/php/ {{php_version}} /fpm `

**Comment by geerlingguy** [comment]
That's one of the paths you need to override when changing PHP versions; please see the way Drupal VM sets all the variables here: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/roles/drupalvm.php-versions/vars/Debian.yml
