### ISSUE TITLE
php_fpm_pool_conf_path ignored

### ISSUE THREAD

**Issue by wshafer** [geerlingguy/ansible-role-php#194]
Just a quick note.  var `php_fpm_pool_conf_path` seems to be getting ignored.  I have been able to update everything else for php 7.1 but the `www.conf` file is still going to `/etc/php/7.0/fpm/pool.d/www.conf`

**Comment by geerlingguy** [comment]
@wshafer - I'm not sure how that's possible... I'm testing through Drupal VM and it seems to be working—note that the www.conf file is placed in through this task: https://github.com/geerlingguy/ansible-role-php/blob/65f5e3525914b5defa2eae22aae3b833056ec1ff/tasks/configure-fpm.yml#L39

Do you have `php_enable_php_fpm` set to `true`?

Also, note that the role won't clean up older versions of PHP by default (e.g. if you first installed PHP 7.0, then later installed 7.1, the 7.0 file will still exist).

**Comment by wshafer** [comment]
Thanks for looking into this @geerlingguy .  I am no longer on that project and am unable to test this again.  Going to go ahead and close this out.

Thanks again,
Westin
