### ISSUE TITLE
Document easy way to get other versions of PHP to be installed

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#197]
Drupal VM has been hoarding some nifty PHP version management support for some time. I created a ticket over there to get that role extracted so others can use it independent of Drupal VM: https://github.com/geerlingguy/drupal-vm/issues/1377

I've created the repo for this: https://github.com/geerlingguy/ansible-role-php-versions

Now I need to add some documentation in the main README (and maybe a commented variable in `defaults` with a link?) for how you can use that role with this one.

It's actually fairly simple:

  1. Add the `geerlingguy.php-versions` role.
  2. Set `php_version: 7.1` (or `7.0`, or `5.6`, or any supported recent version)
  3. Run the playbook.

It's even smart enough to uninstall PHP and reinstall, if a different version is currently installed. At least, most of the time.

**Comment by jasperf** [comment]
I see ansible-role=php is a soft dependency as the `php_version` variable needs to be set. Does this mean I would a standard setup with vars minus setting the paths and your PHP and PHP versions role will take care of the rest? 
For the PHP packages I choose I will then only have to add package names and no version numbers?

**Comment by geerlingguy** [comment]
@jasperf - mostly, yes. You can add more PHP packages using the `php_packages_extra` variable (I think that's it, going from memory here), or if you don't need all the ones this role/the versions role bundles, you can override `php_packages` (but keeping the `php_version` variable in each package name, if you're on Ubuntu/Debian).
