### ISSUE TITLE
PHP Memory_Limit loaded from /etc/php/7.1/fpm/php.ini instead of vars/main.yml

### ISSUE THREAD

**Issue by jasperf** [geerlingguy/ansible-role-php#198]
Despite my vars/main.yml loading php values the memory limit is still set at 128M instead of 512M. It somehow seems to load it from `/etc/php/7.1/fpm/php.ini`:
````
 /etc/php/7.1/fpm/php.ini | grep memory
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 128M
````
instead of this from vars/main.yml:
````
php_version: "7.1"
php_packages_state: latest
php_use_managed_ini: true
php_memory_limit: "512M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php7.1-apcu
  - php7.1-common
  - php7.1-intl
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php-mbstring
  - php7.1-mcrypt
  - php7.1-opcache
  - php7.1-pdo
  - php7.1-xml
  - php7.1-mbstring
  - php7.1-zip
  - php7.1-mysql
php_date_timezone: "Europe/Amsterdam"
php_webserver_daemon: "nginx"
php_fpm_daemon: php7.1-fpm
````
repo in progress here https://github.com/jasperf/stedding 

Any ideas why and how I can solve this issue?

**Comment by oxyc** [comment]
You also need to update `php_conf_paths` https://github.com/geerlingguy/ansible-role-php-versions/blob/master/vars/Debian.yml#L3:L6

**Comment by geerlingguy** [comment]
As @oxyc says, you need to update that path. Also, note that there's a new role that was broken out of Drupal VM to allow for much easier PHP version switching with this role: https://github.com/geerlingguy/ansible-role-php-versions

**Comment by jasperf** [comment]
@oxyc Thanks. Yeah, it seems I needed to add:
```
php_conf_paths:
  - /etc/php/7.1/fpm
  - /etc/php/7.1/cli

php_extension_conf_paths:
  - /etc/php/7.1/fpm/conf.d
  - /etc/php/7.1/cli/conf.d
```
as well. Which I did not. Thanks so much for pointing this out!
@geerlingguy Yeah, you mentioned the new role with easier PHP versioning in another ticket. Can't wait to see it. Thanks for all the hard work and the sharing of it all!
