### ISSUE TITLE
PHP-7.0 does not exist on Debian Jessie

### ISSUE THREAD

**Issue by Typnix** [geerlingguy/ansible-role-php#199]
When executing the role on Debian. It fails to install PHP because it tries to install 7.0 which doesn't exist yet on Debian Jessie. Debian Jessie still distributes PHP 5 at default.

**Comment by geerlingguy** [comment]
Please see this role's built-in tests, which show you how to get the right apt repository set up for 7.0. Also, check out `geerlingguy.php-versions` (https://github.com/geerlingguy/ansible-role-php-versions) for easier version changing with this role. As it is right now, if you want PHP 5.6 on Jessie, you have to manually override a bunch of paths, the packages, etc.—the versions role makes that really easy.
