### ISSUE TITLE
Unexpected version of PHP installed

### ISSUE THREAD

**Issue by walterdolce** [geerlingguy/ansible-role-php#205]
Hi,

With the help of https://github.com/geerlingguy/ansible-role-php-versions, I just provisioned a VM with test-kitchen. But even though I have specifically set the `php_version` Ansible variable to `5.6` (along with a list of some 5.6-related `php_packages_extra`), when I went into the VM and checked the version of PHP with `php -v` I got `7.1.7` instead of `5.6` ?

Is that expected?

**Comment by walterdolce** [comment]
Update. 

Looks like on the *first* provisioning run it installs `5.6` **as well as** `7.1`. Then, on the second provisioning run it *removes* `7.1` and it leaves only `5.6` (which I wanted).

Is this still expected?

As this can be quite a blocker for those who want to use your role. I.e. people wanting to provision an AMI (which is a one-off operation) will have to drop using this role. 

Hope that makes sense. Thank you.

**Comment by geerlingguy** [comment]
@walterdolce -  There are a number of ways two versions of PHP might be getting installed.

In my usage with Drupal VM and in other projects, it only installs one version straightaway. But if you have any other provisioning taking place before this role (and `geerlingguy.php`) runs, or if you modify `php_packages` or `php_packages_extra` in your playbook's variables, it could have some unexpected results.

Can you produce a configuration and/or playbook that results in this error? Or at least provide any overridden variables you're using?

**Comment by geerlingguy** [comment]
Specifically, what do you have set for `php_packages_extra`?

**Comment by walterdolce** [comment]
I realised I was using a configuration of variables which was leading to that.

With the following variables, instead, I get the role to install and "activate" the correct version (note that in `/etc/php` I still get the `5.6`, `7.0` and `7.1` created..):
```
php_install_recommends: no
php_conf_paths:
  - "/etc/php/{{ php_version }}/fpm"
  - "/etc/php/{{ php_version }}/apache2"
  - "/etc/php/{{ php_version }}/cli"

php_version: "5.6"
php_packages:
  - php5.6
  - php5.6-mbstring
  - php5.6-dom
  - php5.6-bcmath
  - php5.6-mysql
  - php5.6-curl
  - php5.6-intl
  - php5.6-cli
  - php5.6-redis
  - php5.6-mcrypt
  - php5.6-gd
  - php5.6-json
  - pdftk
  - libapache2-mod-php5.6
```

Obviously `php_version` in this instance is set to `5.6`.

`php_packages_extra` has the following:
```
    php_packages_extra:
      - "libapache2-mod-php5.6"
      - "php5.6-bcmath"
      - "php5.6-intl"
      - "php5.6-mysql"
      - "php-pear"
```

**Comment by walterdolce** [comment]
With the configuration above I don't get the unexpected PHP version "activated" (which means when I do `php -v` I get `5.6` as I would expect). So as far as I'm concerned this issue can be closed unless you spotted something given the info above. :)

**Comment by geerlingguy** [comment]
Sounds good to me—all's well that ends well! I think the current situation (where there are some notable differences in some packages between 5.6 and 7.[current]) is going to continue to cause some weird things to happen from time to time.
