### ISSUE TITLE
Installation of "php" package will install mod_php and php.conf file

### ISSUE THREAD

**Issue by jamieburchell** [geerlingguy/ansible-role-php#215]
If you want to install PHP and use PHP-FPM exclusively, you need to somehow remove or overwrite the php packages configuration value so that "php" isn't installed. In EL6 and EL7 at least, the installation of the "php" package installs mod_php and enables the handler with PHP files.

I believe with this role, by default, if you enable PHP FPM, you'll also have mod_php and the PHP/Apache handler installed.

**Comment by FinBoWa** [comment]
The `php_packages` under https://github.com/geerlingguy/ansible-role-php#role-variables  is what you are looking for if you want to override it

**Comment by jamieburchell** [comment]
Yes. But I wonder, how many people enable PHP-FPM thinking they are using this instead of mod_php, without realising that mod_php will be installed and enabled aswell?

**Comment by FinBoWa** [comment]
Id suspect that is more common to install more than make it lean from the get go. I'd argue that leaving packages is system optimisation and if you are actually doing that youd override all the packages that just toggling one away with a condition.

**Comment by FinBoWa** [comment]
Actually I meant on writing limiting not leaving  :)

**Comment by virain** [comment]
I also found this problem
