### ISSUE TITLE
php_session_gc_probability: 1 overwrites Ubuntu default

### ISSUE THREAD

**Issue by stephankn** [geerlingguy/ansible-role-php#216]
The role specifies a default setting for php.ini:

```
php_session_gc_probability: 1
```

This conflicts with the default setting of at least Ubuntu 16.04 LTS (and probably other debian based setups). These turn gc off by default and install a cron job to clean up sessions every 30 minutes:

```
# cat /etc/cron.d/php
# /etc/cron.d/php@PHP_VERSION@: crontab fragment for PHP
#  This purges session files in session.save_path older than X,
#  where X is defined in seconds as the largest value of
#  session.gc_maxlifetime from all your SAPI php.ini files
#  or 24 minutes if not defined.  The script triggers only
#  when session.save_handler=files.
#
#  WARNING: The scripts tries hard to honour all relevant
#  session PHP options, but if you do something unusual
#  you have to disable this script and take care of your
#  sessions yourself.

# Look for and purge old sessions every 30 minutes
09,39 *     * * *     root   [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean
```

I suggest to change the default to `php_session_gc_probability: 0` to keep the ubuntu process functional.

Seems to be in line with the PHP documentation also considering the request-based GC flawed.
http://php.net/manual/en/function.session-gc.php

**Comment by stephankn** [comment]
The issue still exists with Ubuntu 18.04.4 LTS.

**Comment by stephankn** [comment]
as of today, problem still exists.

**Comment by stephankn** [comment]
issue still current. I linked a PR to change the default

**Comment by geerlingguy** [comment]
I typically keep this role using the PHP defaults where possible, and note that the current default seems to still be `1`: https://www.php.net/manual/en/session.configuration.php#ini.session.gc-probability

**Comment by stephankn** [comment]
I understand, that the default value of config of php.net is 1. Still, the same php.net documentation recommends to change this. And on setups running Ubuntu it is broken when installing PHP with this role, as then two conflicting settings are enabled. So at least for Ubuntu I consider it as a bug. Either the value has to be 0 on Ubuntu or the cron-job on Ubutu needs to be disabled.

**Comment by stephankn** [comment]
any update in merging this?

**Comment by stephankn** [comment]
This point is still relevant and I would like to see the change merged

**Comment by stephankn** [comment]
still valid

**Comment by racke** [comment]
Makes sense to me as well

**Comment by stephankn** [comment]
this is still relevant

**Comment by stephankn** [comment]
Hey, stale bot. This issue is still valid. Remove the label.

**Comment by stephankn** [comment]
I still consider this valid
