### ISSUE TITLE
When apc is enabled the role cannot be provisioned twice

### ISSUE THREAD

**Issue by CharlyP** [geerlingguy/ansible-role-php#22]
Hi,

I have problems provisioning my environment with `php_enable_apc` set as `true`.

The first provisioning goes well but if I try to redo it I have the following error:
```
failed: [default] => {"failed": true, "gid": 0, "group": "root", "mode": "0777", "owner": "root", "path": "/etc/php5/apache2/conf.d/20-apc.ini", "size": 25, "src": "apc.ini.j2", "state": "link", "uid": 0}
msg: src file does not exist, use "force=yes" if you really want to create the link: /etc/php5/apache2/conf.d/apc.ini.j2
```

Tell me if you miss some information to reproduce.

Kind regards,

**Comment by geerlingguy** [comment]
This should be fixed as a result of the configuration file fixes in #17. Please reopen if that's not the case. Thanks!
