### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by san4io** [geerlingguy/ansible-role-php#225]
Hello, we need support for PHP 7.2. :)

**Comment by bmack** [comment]
yeah, looking for something similar to get PHP 7.2 with Ansible installed "by default".

Would be interesting to know if the role should allow to activate third-party PPAs somehow via a special option, and to install `php-7.2-*` packages simply listed in the `php_packages` variable.

**Comment by dqlopez** [comment]
Badly need this neat feature but it seems that this is never even tagged :( @geerlingguy

**Comment by san4io** [comment]
Well actually use https://github.com/geerlingguy/ansible-role-php-versions, and in vars set: 
```
php_version: '7.2'
```

**Comment by geerlingguy** [comment]
What @san4io said ^^

This role is meant to be more simple in setting up and configuring PHP; the PHP versions role takes care of the (in many ways way more complex) task of allowing for different versions of PHP, easily.

You can install 5.6, 7.0, 7.1, 7.2 using that role; see the link in the comment above.

**Comment by JasperAlgra** [comment]
@geerlingguy Maybe mention this in the readme? After looking there for some clues about switching versions I tried changing `php_packages_state` to `latest`. 
After that it took quite some time to find your other package (php-versions) which helped. But it's not that obvious if you don't know what you are looking for.
