### ISSUE TITLE
Error "No package matching 'php7.0-common' is available"

### ISSUE THREAD

**Issue by flaugher** [geerlingguy/ansible-role-php#226]
I'm getting the error in the title when I try to install geerlingguy.php.  Here is the output:

PLAY [Install LAMP] ************************************************************

TASK [setup] *******************************************************************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : Include OS-specific variables.] *********************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : Include variables for Amazon Linux.] ****************
skipping: [cms00.jones.com]

TASK [geerlingguy.apache : Define apache_packages.] ****************************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : include] ********************************************
included: /Users/jones/playbooks/lamp/roles/geerlingguy.apache/tasks/setup-Debian.yml for cms00.jones.com

TASK [geerlingguy.apache : Update apt cache.] **********************************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
ok: [cms00.jones.com] => (item=[u'apache2', u'apache2-utils'])

TASK [geerlingguy.apache : Get installed version of Apache.] *******************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : Create apache_version variable.] ********************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : include_vars] ***************************************
skipping: [cms00.jones.com]

TASK [geerlingguy.apache : include_vars] ***************************************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : include] ********************************************
included: /Users/jones/playbooks/lamp/roles/geerlingguy.apache/tasks/configure-Debian.yml for cms00.jones.com

TASK [geerlingguy.apache : Configure Apache.] **********************************
ok: [cms00.jones.com] => (item={u'regexp': u'^Listen ', u'line': u'Listen 80'})

TASK [geerlingguy.apache : Enable Apache mods.] ********************************
ok: [cms00.jones.com] => (item=rewrite.load)
ok: [cms00.jones.com] => (item=ssl.load)
ok: [cms00.jones.com] => (item=headers.load)

TASK [geerlingguy.apache : Disable Apache mods.] *******************************

TASK [geerlingguy.apache : Check whether certificates defined in vhosts exist.] 

TASK [geerlingguy.apache : Add apache vhosts configuration.] *******************
skipping: [cms00.jones.com]

TASK [geerlingguy.apache : Add vhost symlink in sites-enabled.] ****************
skipping: [cms00.jones.com]

TASK [geerlingguy.apache : Remove default vhost in sites-enabled.] *************
ok: [cms00.jones.com]

TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
ok: [cms00.jones.com]

TASK [geerlingguy.php : Include OS-specific variables.] ************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_packages.] **********************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define extra php_packages.] ****************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_webserver_daemon.] **************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_conf_paths.] ********************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_extension_conf_paths.] **********************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_apc_conf_filename.] *************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_opcache_conf_filename (Ubuntu 16.04).] ******
skipping: [cms00.jones.com]

TASK [geerlingguy.php : Define php_opcache_conf_filename.] *********************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Define php_fpm_conf_path.] *****************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : include] ***********************************************
skipping: [cms00.jones.com]

TASK [geerlingguy.php : include] ***********************************************
included: /Users/jones/playbooks/lamp/roles/geerlingguy.php/tasks/setup-Debian.yml for cms00.jones.com

TASK [geerlingguy.php : Update apt cache.] *************************************
ok: [cms00.jones.com]

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [cms00.jones.com] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'php-sqlite3', u'php-apcu', u'libapache2-mod-fastcgi']) => {
    "failed": true, 
    "item": [
        "php7.0-common", 
        "php7.0-cli", 
        "php7.0-dev", 
        "php7.0-fpm", 
        "libpcre3-dev", 
        "php7.0-gd", 
        "php7.0-curl", 
        "php7.0-imap", 
        "php7.0-json", 
        "php7.0-opcache", 
        "php7.0-xml", 
        "php7.0-mbstring", 
        "php-sqlite3", 
        "php-apcu", 
        "libapache2-mod-fastcgi"
    ]
}

MSG:

No package matching 'php7.0-common' is available

PLAY RECAP *********************************************************************
cms00.jones.com    : ok=25   changed=0    unreachable=0    failed=1   

I tried setting "php_packages_state: latest" in my vars/main.yml file but that didn't help.  Is there another way to circumvent this error?  Thanks.

**Comment by senorsmile** [comment]
Which OS?  What vars did you have set?

**Comment by trindium** [comment]
Im in the same place.

Debian 8, 

php_memory_limit: "1024M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-cli
  - php-curl
  - php-gd
  - php-json
  - php-mongo
  - php-mysql
  - php-xdebug



Thnx

**Comment by Lusitaniae** [comment]
Try `apt update ` before

**Comment by josc360** [comment]
I managed to solve this by adding:

- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

To setup-Debian.yml

Hope it helps!

**Comment by aur1mas** [comment]
if you want to use php version different then distro (OS) default, you should add `geerlingguy/php-versions` & define your version.

**Comment by geerlingguy** [comment]
Yeah, the `geerlingguy.php-versions` role is the best way to switch between different PHP versions using this role as a base, and it makes it as easy as `php_version: [5.6|7.0|7.1|7.2]` (pick your version). Otherwise you'd need to add a repo and/or override the php_packages list yourself.

Closing as a won't fix, as the recommendation is to use the versions role for ease of use, or manage it yourself if you need a more specialized setup.

**Comment by ljerome83** [comment]
very clear, thanks

**Comment by flaugher** [comment]
Thanks, but in reply to aur1mas, I'm not choosing to use a different PHP version.  The Debian.yml module in geerlingguy.php is choosing that version.  Shouldn't it know that that version isn't available by default and select one that is?  Thanks.

**Comment by tamusjroyce** [comment]
php_default_version_debian in debian.yml was coming through as 7.0? Even though php_version was set to 7.2. The below seems to fixed it for me. Maybe there is a better way or I am missing something?

```
---
- hosts: all
  vars:
    php_version: '7.2'
    php_default_version_debian: '7.2'
  roles:
  - geerlingguy.php

```
