### ISSUE TITLE
Unable to retrieve file contents

### ISSUE THREAD

**Issue by dupuchba** [geerlingguy/ansible-role-php#227]
I am currently trying to install php 7.1 on my vagrant VM with ansible and this role but I've got this error and I am really struggling to correct it.

```
fatal: [XXX.dev]: FAILED! => {"failed": true, "reason": "Unable to retrieve file contents Could not find or access '/Users/XXX/Projects/php/projects/XXX/XXX-app/ansible/setup-Debian.yml'"}
```

any one has a clue on this one ? 

Thanks a lot :-)

**Comment by apphancer** [comment]
Same problem here when spinning up on a DO droplet.

`fatal: [server-4]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/Users/m/hosts/ansible-do-playbook/setup-Debian.yml'"}`

The correct path should in fact be:
/Users/m/hosts/ansible-do-playbook/vendor/roles/geerlingguy.php/tasks/setup-Debian.yml

**Comment by apphancer** [comment]
I have managed to solve this issue by upgrading ansible from 2.4.2.0 to 2.8.2
