### ISSUE TITLE
Proposal: use Software Collections on Red Hat and CentOS distributions  

### ISSUE THREAD

**Issue by bngsudheer** [geerlingguy/ansible-role-php#228]
Software Collections offers many versions of PHP: https://www.softwarecollections.org/en/scls/?search=php

Would you accept a PR that allows installing and configuring PHP packages via SCL?

**Comment by dragon-bn** [comment]
Hello,
Could you change the role to take into account the "Software Collections" repository, with its specificities of installations?
cordially
Stéphane
