### ISSUE TITLE
Unable to lock the administration directory

### ISSUE THREAD

**Issue by passionventures** [geerlingguy/ansible-role-php#238]
We have encountered another issue that we're trying to solve on Amazon EC2.

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************************************
failed: [18.130.7.212] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'php-sqlite3', u'php-apcu']) => {"cache_update_time": 1525689711, "cache_updated": false, "changed": false, "item": ["php7.0-common", "php7.0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "php7.0-gd", "php7.0-curl", "php7.0-imap", "php7.0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php-sqlite3", "php-apcu"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php7.0-common' 'php7.0-cli' 'php7.0-dev' 'php7.0-fpm' 'libpcre3-dev' 'php7.0-gd' 'php7.0-curl' 'php7.0-imap' 'php7.0-json' 'php7.0-opcache' 'php7.0-xml' 'php7.0-mbstring' 'php-sqlite3' 'php-apcu' -o APT::Install-Recommends=yes' failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\n", "rc": 100, "stderr": "E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\n", "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)", "E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?"], "stdout": "", "stdout_lines": []}

Maybe someone knows what's the issue.

Thank you,
Jakub

**Comment by geerlingguy** [comment]
> Unable to lock the administration directory (/var/lib/dpkg/), are you root?

Means you're running the role as a non-root / unprivileged user.

When you call the role, use `become: yes`, e.g.:

```yaml
  roles:
    - name: geerlingguy.php
      become: yes
```

**Comment by deepcore** [comment]
Hi @geerlingguy 
Thank you, for your answer. In the end, I've done it like you said.
I have used a lot of your roles for our AWS and Digital Ocean servers cloud automation.
Works fantastic :)
Thank you,
Jakub
