### ISSUE TITLE
Problem with updated Ubuntu 18.04.01

### ISSUE THREAD

**Issue by Uccio** [geerlingguy/ansible-role-php#252]
If you try the example configuration in Ubuntu 18.04.01

The execution stops in TASK [geerlingguy.php : Ensure PHP packages are installed.] with the following error

> TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
> failed: [servertarget] (item=[u'php7.2', u'php7.2-apcu', u'php7.2-cli', u'php7.2-common', u'php7.2-curl', u'php7.2-dev', u'php7.2-fpm', u'php7.2-gd', u'php7.2-imap', u'php7.2-json', u'php7.2-mbstring', u'php7.2-opcache', u'php7.2-sqlite3', u'php7.2-xml', u'php7.2-yaml']) => {"cache_update_time": 1536327545, "cache_updated": false, "changed": false, "item": ["php7.2", "php7.2-apcu", "php7.2-cli", "php7.2-common", "php7.2-curl", "php7.2-dev", "php7.2-fpm", "php7.2-gd", "php7.2-imap", "php7.2-json", "php7.2-mbstring", "php7.2-opcache", "php7.2-sqlite3", "php7.2-xml", "php7.2-yaml"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php7.2-apcu' 'php7.2-curl' 'php7.2-dev' 'php7.2-fpm' 'php7.2-gd' 'php7.2-imap' 'php7.2-mbstring' 'php7.2-sqlite3' 'php7.2-xml' 'php7.2-yaml' -o APT::Install-Recommends=no' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n php7.2-imap : Depends: libc-client2007e but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " php7.2-imap : Depends: libc-client2007e but it is not installable"]}

The problem seems to be:

> The following packages have unmet dependencies:
>  php7.2-imap : Depends: libc-client2007e but it is not installable
> E: Unable to correct problems, you have held broken packages.

I try to fix the problem with configuration like this:

php_packages:
  - php
  - php-cli
  - php-common

but ... I was not lucky

**Comment by geerlingguy** [comment]
@Uccio - The test playbook (https://github.com/geerlingguy/ansible-role-php/blob/master/tests/test.yml) seems to work okay on 18.04.01, but maybe it's an issue with Ondrej's packages for PHP 7.2? I would look into that. See if using PHP 7.1 (easiest way is to use my `geerlingguy.php-versions` role) fixes the problem, and that would probably indicate it's an issue with the repo currently.

**Comment by logan2211** [comment]
Please see #249

**Comment by tehtbl** [comment]
Hi! I had the same issue on an up-to-date Ubuntu 18.04.1 LTS. Seems that the current LTS uses a PHP 7.2. So, putting the following line in your `vars` section of your playbook can be used as a quick fix: 
```
php_default_version_debian: "7.2"
```

**Comment by memelet** [comment]
I built using ubuntu 19 with `php_default_version_debian: 7.2`. Now I am running on ubuntu 16 and I get errors for pretty much all the php modules
```
msg: No package matching 'php7.2-common' is available
```

**Comment by memelet** [comment]
Added your php-versions role and it now runs :-)
