### ISSUE TITLE
Can't get php-fpm to work

### ISSUE THREAD

**Issue by MFProduction** [geerlingguy/ansible-role-php#256]
I am having an issue with setting up php-fpm on ubuntu 18.04 with the following error:
`fatal: [default]: FAILED! => {"changed": false, "msg": "Error when trying to enable php7.2-fpm: rc=1 Failed to enable unit: Unit file php7.2-fpm.service does not exist.\n"}
`
What am i missing?

**Comment by Magentron** [comment]
@MFProduction May I ask what was the problem and how you solved it? I have the same issue.

**Comment by Magentron** [comment]
This may have been the solution:
https://github.com/geerlingguy/ansible-role-php/issues/151#issuecomment-265960386
