### ISSUE TITLE
No package matching 'php7.1' is available

### ISSUE THREAD

**Issue by Drew-Kimberly** [geerlingguy/ansible-role-php#264]
Hi,

Our CI builds using this role started failing this weekend with the following error:

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'php7.1' is available"}
```

Related: https://github.com/geerlingguy/drupal-vm/issues/1928

**Comment by geerlingguy** [comment]
Can you give more details on how to reproduce this issue? What OS are you running, and can you reproduce the issue anywhere besides your Drupal VM configuration?

The CI builds are all passing (https://travis-ci.org/geerlingguy/ansible-role-php), and the php-versions CI builds are also all passing. Note that some OSes do not include php7.1 in their package repos, so you'd have to be using the php-packages repo or some other repository for anything like that to work.

Additionally, if using Ubuntu 14.04, support has ended for it entirely and the package maintainer(s) who were supporting it have also stopped publishing newer PHP packages for it (in case you're running 14.04).

**Comment by Drew-Kimberly** [comment]
Thanks for the response @geerlingguy!

Closing this, we're on 14.04 and I see the PHP packages were just removed for that here: https://launchpad.net/~ondrej/+archive/ubuntu/php
