### ISSUE TITLE
Make it possible to set additional OpCache settings

### ISSUE THREAD

**Issue by josefglatz** [geerlingguy/ansible-role-php#270]
e.g. for one important undocumented option `opcache.fast_shutdown`.

Would be really nice, thanks

**Comment by ElijahLynn** [comment]
Are there more than this? Will be faster to get in if you just want a few settings than to change functionality to accept any setting. 

I think you could make a PR easily for this, changes would be here:
* [defaults](https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml)
* [task file](https://github.com/geerlingguy/ansible-role-php/blob/master/templates/opcache.ini.j2)
* readme
