### ISSUE TITLE
How to minor-update PHP version?

### ISSUE THREAD

**Issue by smknstd** [geerlingguy/ansible-role-php#287]
Can this role update php (and extensions) with latest minor update available (eg: going from 7.2.24 to 7.2.27) ?

Like I would do with apt: `sudo apt-get install --only-upgrade php7.2*`

Thanx

**Comment by smknstd** [comment]
@geerlingguy Is it obvious or something ?

**Comment by geerlingguy** [comment]
@smknstd - You can set `php_packages_state` to `latest` and that will install the latest version of the packages that are configured on the system (e.g. 7.2.1 to 7.2.3 or whatever's latest).

You can also use the `geerlingguy.php-versions` role to switch versions more easily.

**Comment by smknstd** [comment]
Ok but what if in my case latest available is another major release (let's say 7.4) ? If I use `php_packages_state: latest` I won't get what I want : the last security patch available for 7.2 but I'll get a new major release. Am I right ?

My question was, how can I keep my php version updated with latest security patch if it isn't the latest major version of php available ?

Thanx a lot for your help.

**Comment by geerlingguy** [comment]
@smknstd - For any of the normal system packages (e.g. Debian/Ubuntu/CentOS/etc.) they only provide one major version for updates, so CentOS 6 does like 5.4.x (but not 5.5.x or later), Debian 10 does 7.3.x (but not 7.4.x or later).

And if you pair this with the `geerlingguy.php-versions` role and set `php_version: 7.3` that will keep you locked into 7.3.x and never allow an upgrade to 7.4.x (it uses Remi's repositories on CentOS/RH or Ondrej's repositories on Ubuntu/Debian).

**Comment by smknstd** [comment]
Thanx again ! It is now super clear how to do that. Would you accept any suggestion on the README ? In my opinion it could have a section dedicated to php version to make this clearer.

Have a good day.
