### ISSUE TITLE
TASK Ensure php-fpm is started ... fails on nodes with python3

### ISSUE THREAD

**Issue by jfoliveira** [geerlingguy/ansible-role-php#288]
Hi,

As `ansible` docs and warnings recommend the adoption of python version 3, and as [python 2 reached its end of life](https://www.python.org/doc/sunset-python-2/) I recently updated my managed nodes to python 3.

So far almost everything works fine, with many proprietary and open source roles (thanks @geerlingguy for your great and generous work sharing so many useful roles with us).

One issue that I've found is during the execution of the task: `Ensure php-fpm is started and enabled at boot (if configured).`

Complete exception message:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 109: ordinal not in range(128)
fatal: [172.17.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_service_payload_s7zrkh0t/ansible_service_payload.zip/ansible/modules/system/service.py\", line 1669, in <module>\n  File \"/tmp/ansible_service_payload_s7zrkh0t/ansible_service_payload.zip/ansible/modules/system/service.py\", line 1611, in main\n  File \"/tmp/ansible_service_payload_s7zrkh0t/ansible_service_payload.zip/ansible/modules/system/service.py\", line 699, in service_enable\n  File \"/usr/lib/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 109: ordinal not in range(128)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

**My setup:**

- Control node: Debian 8.10 (jessie), python 2.7
- Ansible version: 2.9.4 (also reproduced the same issue with Ansible 2.8)
- Managed node: Ubuntu 18.04 (bionic), python 3.6

I couldn't find anything wrong or suspicious [in the task source code implementation](https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/configure-fpm.yml#L72) itself.

Any ideas or suggestions on how to further investigate this issue?

**Comment by geerlingguy** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 109: ordinal not in range(128)

I've hit this from time to time with Python 3.6... not sure if the problem still exists with 3.7—though I have not seen this problem with this role in particular.

**Comment by jfoliveira** [comment]
I understand this might not be an issue with this role and perhaps an issue with ansible `service` module, but given it's intermittency might be a good idea to use the `command` module instead.

I found a similar issue on [geerlingguy/ansible-role-mysql repository](https://github.com/geerlingguy/ansible-role-mysql/issues/265)

A few extra info, not sure if it's helpful:

1) I could It's reproducible with the simplified playbook below:
```
- hosts: all
  gather_facts: no

  tasks:
  - name: Ensure php-fpm is started and enabled at boot (if configured).
    service:
      name: "php7.2-fpm" # testing with `mysql`, `ssh` and `supervisor` services the error was not reproduced
      state: started
      enabled: true # the issue only happens when setting the `enabled` property, being it true or false, with `php7.2-fpm` service
```
2) As it can be noticed in the playbook comments above, there is something specific to `php7.2-fpm` service when the service module try to enable it to auto start on boot.

**Comment by jfoliveira** [comment]
I reported the issue on `ansible` repo: https://github.com/ansible/ansible/issues/67293
As this is actually by the `service` core module.

**Comment by kayue** [comment]
What is the solution to this?
