### ISSUE TITLE
Use Systems timezone by default

### ISSUE THREAD

**Issue by e1mo** [geerlingguy/ansible-role-php#314]
I would propose a new variable, such as `+php_date_timezone_from_sytem` as a boolean, to use the Systems Timezone by default in PHP. I personally would go with `true` as a default. If it's set to true, it would the default value for `php_date_timezone` with the systems timezone.
I tried to implement it, but found one problem. How to get the Systems time in `Region/City` notation with ansible? There is the `ansible_date_time.tz` but it's only the short form such as `CDT`, `CEST` and so on. And those are not aware of summer and winter time (e.g. `Europe/Berlin` is in the winter `+02:00` and in the summer `+01:00` but the corresponding `CEST` will always be `+02:00`), therefore being of by an hour half of the year.

Does anyone has an Idea how to solve that? I would happily do the implementation itself!

**Comment by nono-lqdn** [comment]
Not completed . 

I would also like to have some way to configure the role for this.
