### ISSUE TITLE
No package matching 'php-devel' found available, installed or updated

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/ansible-role-php#328]
In the vars/RedHat.yml 

__php_packages:
contans:
  - php-devel

but this cannot be installed in my environment. Is this strictly needed for the moduile to work or can this be caught in another  vars (php-extra packages)

**Comment by dspolleke** [comment]
I checked but is not in de "general" repo but in the extra-packages repo so to put it in the default install is nog really a good idea.

**Comment by kindlehl** [comment]
@dspolleke this role is for setting up PHP. It would be expected that your environment is setup to allow the role to work. There is no better way to get PHP on your server than going through EPEL or IUS.

**Comment by dspolleke** [comment]
Well, the rest of the packages are NOT in epel. -devel packages have no
place on production servers.
