### ISSUE TITLE
Allow `remi_repo_gpg_key_url` and `remi_repo_gpg_key_url` to pass to remi role

### ISSUE THREAD

**Issue by indytechcook** [geerlingguy/ansible-role-php#337]
It doesn't appear there is a way to pass the `remi_repo_gpg_key_url` or `remi_repo_gpg_key_url` to your `repo-remi` role.  This would allow for the selection of the closest mirror.  

If this is already possible, I'm sorry I couldn't figure it out.  

cc @ElijahLynn

**Comment by ElijahLynn** [comment]
Hrm, I wonder if the gpg keys are on the mirrors. 

![image](https://user-images.githubusercontent.com/1504756/127524719-f7789a05-e08b-416e-913a-c019e6d00528.png)

**Comment by geerlingguy** [comment]
@indytechcook - You can override both variables in your playbook:

```yaml
remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
remi_repo_gpg_key_url: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
```

Those are defined as defaults in the repo-remi role: https://github.com/geerlingguy/ansible-role-repo-remi/blob/master/defaults/main.yml

But as @ElijahLynn mentions, they may not be mirrored on the official mirrors...

**Comment by indytechcook** [comment]
@geerlingguy can we pass them to the PHP playbook?

**Comment by indytechcook** [comment]
Sorry, I withdraw my comment, @ElijahLynn is teaching me more about how this works in ansible. I need to finish your book :)

**Comment by ElijahLynn** [comment]
> But as @ElijahLynn mentions, they may not be mirrored on the official mirrors...

It doesn't appear the GPG Keys are mirrored (https://forum.remirepo.net/viewtopic.php?pid=11935#p11935 and https://twitter.com/RemiRepository/status/1420625963419947009).

Hosting the key elsewhere, e.g. S3 (as Neil suggested outside this thread) and overriding the default `remi_repo_gpg_key_url` in the playbook where we call the role would work. The GPG Key endpoint appears to be stable again now but this will likely happen again in the future (not if but when).

**Comment by remicollet** [comment]
Install the **distribution-gpg-keys** package (from EPEL) which provides lot of 3rd party repo keys ;)

**Comment by remicollet** [comment]
And you can also use the cdn for this
* EL-7: http://cdn.remirepo.net/RPM-GPG-KEY-remi
* EL-8: http://cdn.remirepo.net/RPM-GPG-KEY-remi2018

the **cdn** is a small set of servers (2 for now), only used for small "critical" traffic, usually the mirrorlist

**Comment by geerlingguy** [comment]
@remicollet - Oh, nice! Thanks for the updates, and again thanks for your work keeping the PHP world going 'round in RHEL land. I've created a follow-up issue for implementation: https://github.com/geerlingguy/ansible-role-repo-remi/issues/27

**Comment by Lusitaniae** [comment]
> And you can also use the cdn for this
> 
> * EL-7: http://cdn.remirepo.net/RPM-GPG-KEY-remi
> * EL-8: http://cdn.remirepo.net/RPM-GPG-KEY-remi2018
> 
> the **cdn** is a small set of servers (2 for now), only used for small "critical" traffic, usually the mirrorlist (no https available)

Wonder if the keys could be served from an actual CDN?
