### ISSUE TITLE
Cannot use handlers from this role if running playbook with tags

### ISSUE THREAD

**Issue by sebastianmacarescu** [geerlingguy/ansible-role-php#348]
I'm using this role in a task with tags as follows:
`- name: Create .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ install_path }}/.env"
  notify: restart webserver
  tags: ['configuration', 'configuration:app']`

I'm running the playbook with `--tags "configuration:app"`

I get the following error:
`msg: |-
    The task includes an option with an undefined variable. The error was: 'php_fpm_daemon' is undefined

    The error appears to be in '/root/.ansible/roles/geerlingguy.php/handlers/main.yml': line 9, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

    - name: restart php-fpm
      ^ here`

The solution is pretty simple.
Add `always` tag for all tasks in this role that load variables.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never

That is:
* https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
* https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L3
*  https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L10
* https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L15

I can provide a PR if needed

**Comment by racke** [comment]
Yes that makes sense to me. I'm already using that approach for one of my roles.

**Comment by racke** [comment]
It will be difficult to fix that though, because the tasks defining the variables are all over the place. Also the role uses include_tasks instead of import_tasks, so always tag wouldn't help for these tasks.
