### ISSUE TITLE
Support compiling from source, PHP 7, and beyond!

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#35]
Partly inspired by Rasmus' presentation [Speeding up the web with PHP7](http://talks.php.net/fluent15#/), and also from my personal desire to compare some things in Drupal 8 between in 5.5, 5.6, and 7.x, I'd like to add the ability to install/use PHP7 (or other specific version) by allowing PHP to be installed from source, similar to how I do it in the `geerlingguy.git` Galaxy role.

**Comment by geerlingguy** [comment]
Note that currently, since package-based installation is the only supported install method, you can change versions by using different repositories (like `remi` or `epel` on RedHat/CentOS, or `ondrej` repos on Debian/Ubuntu). But there are usually only stable releases available there.

**Comment by theodorosploumis** [comment]
Php7 from ondrej repos fails. 
I get a 404 error while fetching from `http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/dists/trusty/main/binary-i386/Packages`

**Comment by geerlingguy** [comment]
@theodorosploumis - Yeah, right now ondrej's PHP 7 repo is empty, thus the 404. You can still compile from source on Ubuntu, but if you want a package-based install of PHP 7 (currently alpha 2), your only option is to use Remi's repo on RHEL/CentOS.
