### ISSUE TITLE
Unable to set `pm.status_path`

### ISSUE THREAD

**Issue by doenietzomoeilijk** [geerlingguy/ansible-role-php#350]
Title says it all, really; the current template and vars don't allow you to set `pm.status_path` for a pool, unless I'm missing something obvious — which is far from impossible.

Is this an actual decision or just something that simply never came up and that you're willing to receive a PR for?

**Comment by geerlingguy** [comment]
I think it might be simpler (and more flexible) to add in a variable like `php_fpm_extra_settings`, and then you could define additional settings (any from https://www.php.net/manual/en/install.fpm.configuration.php that aren't already covered).

Then you could define in your playbook:

```yaml
php_fpm_extra_settings: |
  pm.status_path = /my/path/here
```

To achieve that, in the existing template, we'd just need to add a line at the bottom:

```yaml
{{ php_fpm_extra_settings }}
```

And in `defaults/main.yml`, a new setting like:

```
php_fpm_extra_settings: ''
```

(And a line documenting the new setting in README.)

**Comment by shakalandy** [comment]
this would be super helpful, indeed.

But what about folks using multiple pools via `php_fpm_pools`?
Would this extra setting be added to all of the pools? Same values make sense if only defined "per pool", or?

**Comment by geerlingguy** [comment]
@shakalandy - I think (at least from my experience, with smaller installations / single sites), we're starting to get into more narrow use cases, and at that point I'd rather someone forks the role and tailors it to their use case better.

**Comment by steinbrueckri** [comment]
@geerlingguy @shakalandy i have open a PR for this topic.

**Comment by marcin-github** [comment]
It would also fix a couple of other issues (e.g. about clear_env ) and it would fix my issue - because I can't set own environment variables in pool.

**Comment by marcin-github** [comment]
not stale
