### ISSUE TITLE
php8.0-json no installation candidate

### ISSUE THREAD

**Issue by dgibbs64** [geerlingguy/ansible-role-php#358]
Re opening based off this issue that went stale https://github.com/geerlingguy/ansible-role-php/issues/323

php-json package is no longer necessary for PHP 8.0: reference
Because php-json is included in default __php_packages list for Debian-based distributions, installation fails:

E: Package 'php8.0-json' has no installation candidate
Solution: install php{{ php_default_version_debian }}-json package only when php_default_version_debian less than 8.0

Failure output
```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [forest-tools.com]: FAILED! => {
    "cache_update_time": 1643369106,
    "cache_updated": false,
    "changed": false,
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
Package php8.0-json is a virtual package provided by:
  php8.0-phpdbg 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  php8.0-fpm 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  php8.0-cli 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  php8.0-cgi 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  libphp8.0-embed 8.0.14-1+ubuntu20.04.1+deb.sury.org+1
  libapache2-mod-php8.0 8.0.14-1+ubuntu20.04.1+deb.sury.org+1

STDERR:

E: Package 'php8.0-json' has no installation candidate

MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"       install 'php8.0-common' 'php8.0-cli' 'php8.0-dev' 'php8.0-fpm' 'libpcre3-dev' 'php8.0-gd' 'php8.0-curl' 'php8.0-imap' 'php8.0-json' 'php8.0-opcache' 'php8.0-xml' 'php8.0-mbstring' 'php-sqlite3' 'php-apcu' 'php8.0-curl' 'php8.0-xml' 'php8.0-zip' -o APT::Install-Recommends=no' failed: E: Package 'php8.0-json' has no installation candidate
```

**Comment by dgibbs64** [comment]
Its worth noting that I didnt notice this issue with 8.1 so I might but be an issue with 8.0

**Comment by dgibbs64** [comment]
I have done a dirty workaround to get past the issue. Effecting 8.0 and 8.1
https://github.com/dgibbs64/ansible-role-php

**Comment by dgibbs64** [comment]
Not stale

**Comment by SolidRhino** [comment]
I get the same error 👍

**Comment by dgibbs64** [comment]
I can confirm that php-json is not required in php 8 as it is now built-in to php
https://php.watch/versions/8.0/ext-json

**Comment by ortzinator** [comment]
The php_versions role fixes this. If you're using php_versions via the php_roles collection, be aware that the collection hasn't been updated in two years and is using an old version of all of its roles geerlingguy/ansible-collection-php_roles#9

**Comment by dgibbs64** [comment]
The issue still remains you can't install php8 with this role. The purpose of this role is to install versions of PHP.

**Comment by dgibbs64** [comment]
bump

**Comment by plix1014** [comment]
see also https://github.com/geerlingguy/ansible-role-php/issues/380#issuecomment-1374798469

**Comment by dgibbs64** [comment]
@aimfireready the problem is that this role tries to install php8.0-json which doesn't exist for php 8 causing the role to fail if anyone trys to install php 8 with this role

**Comment by aimfireready** [comment]
@dgibbs64 ahh, I see that now. I'm not familiar with Ansible. I thought this was a more general PHP issue. Sorry for the mixup.

In my case--a boring ole' Ubuntu VPS--skipping the attempt to install the JSON module fixed the issue. Maybe there's an equivalent way to "skip" that step in Ansible. I hope you figure it out.
