### ISSUE TITLE
How to listen on a socket?

### ISSUE THREAD

**Issue by Bodenhaltung** [geerlingguy/ansible-role-php#359]
Hi,

there is nothing about it in the `default/main.yaml`.

Can you maybe provide a example with different pools on different sockets?

Thanks!

**Comment by racke** [comment]
Use the _php_fpm_pools_ variable (see README)

     php_fpm_pools:
          - pool_name: www
            ....
          - pool_name: rainloop
            pool_user: "{{ rainloop_unix_user }}"
            pool_group: "{{ rainloop_unix_group }}"
            pool_template: www.conf.j2
            pool_listen: "/run/php-rainloop-fpm.sock"
            pool_pm: dynamic
            pool_pm_max_children: 5
            pool_pm_start_servers: 2
            pool_pm_min_spare_servers: 1
            pool_pm_max_spare_servers: 3
            pool_pm_max_requests: 500
            pool_access_log: /var/log/php-fpm.rainloop.access.log

**Comment by Bodenhaltung** [comment]
Ah, yes...sorry and thanks! ;(
