### ISSUE TITLE
Add support for Ubuntu 2022

### ISSUE THREAD

**Issue by lukasfischer** [geerlingguy/ansible-role-php#380]
Create a vars file Ubuntu-22.yml

---
__php_default_version_debian: "8.1"

**Comment by dietze-ac** [comment]
In Ubuntu 22.04 there is no package php8.1-json. Code is included in an other package-
This packages has to be omitted in __php_packages in the vars file for Ubuntu 22.04.

**Comment by plix1014** [comment]
it works with this config.

[Ubuntu-22.yml.txt](https://github.com/geerlingguy/ansible-role-php/files/10368167/Ubuntu-22.yml.txt)

**Comment by markstos** [comment]
@plix1014 Could you submit a PR with your fix?

**Comment by markstos** [comment]
This version `vars/Ubuntu-22.yml` file worked for me:

https://github.com/geerlingguy/ansible-role-php/blob/23280d5db8f430fe8ede5f3f116ced4796c34522/vars/Ubuntu-22.yml

It lists every file *except* the JSON dep. It' s not the cleanest solution, but it works!

**Comment by pfrenssen** [comment]
There is a fix for the missing php8.0-json package in #358.
