### ISSUE TITLE
CentOS (6) needs additional php-opcache package.

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-php#39]
When installing php on CentOS with remi, IUS or webtatic repository, php-opcache is not installed and no opcache.so is present. This leads to this error:
`Failed loading /usr/lib64/php/modules/opcache.so:  /usr/lib64/php/modules/opcache.so: cannot open shared object file: No such file or directory`

An additional install of php-opcache is required.
remi: php55-opcache or php-56-opcache
IUS: php55u-opcache or php56u-opcache
webtatic: php55w-opcache or php56w-opcache

Then `php_opcache_conf_filename` should be 10-opcache.ini rather than opcache.ini

**Comment by geerlingguy** [comment]
Thanks for pointing this out; I'll try to figure out the best approach to getting it working on CentOS 6 with the different repos... as it is, I've only been using it with CentOS 7 and Ubuntu 12/14, so that's why the recent changes have slipped through :(

**Comment by geerlingguy** [comment]
Also, if you're using an older version of PHP, please make sure you have `php_opcache_enabled_in_ini` set to `false`.

**Comment by geerlingguy** [comment]
I'm also getting this on CentOS 7, FYI: `Failed loading /usr/lib64/php/modules/opcache.so:  /usr/lib64/php/modules/opcache.so: cannot open shared object file: No such file or directory`

**Comment by geerlingguy** [comment]
I think this can be closed—for those on CentOS 6 running older versions of PHP or running a package that's not from Remi's repo, you're on your own setting `php_packages` correctly.

See Drupal VM for an example: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-redhat.yml#L16-L18
