### ISSUE TITLE
How to pin specific version of PHP?

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-role-php#398]
We are experiencing segfaults and suspect it may be PHP 8.1.17 and want to roll back to 8.1.16 or earlier. This issue/thread is to document how to do that, which I am going to figure out and post here. Any suggestions are useful too.

**Comment by neidiom** [comment]
```
php_packages:
  - php8.1-fpm=8.1.17-1+0~20230316.37+debian11~1.gbp0c3ecb
```

make sure the package exists on the server

```
apt-cache showpkg php8.1-fpm
```

**Comment by ElijahLynn** [comment]
Thank you!
