### ISSUE TITLE
"Ensure configuration directories exist." task is never executed 

### ISSUE THREAD

**Issue by zeroespace** [geerlingguy/ansible-role-php#40]
on Ubuntu 14.04 LTS I noticed that the "Ensure configuration directories exist".

here is the execution log on my server

TASK: [geerlingguy.php | Include OS-specific variables.] ********************** 
ok: [*********]

TASK: [geerlingguy.php | Define php_packages.] ******************************** 
skipping: [*********]

TASK: [geerlingguy.php | Ensure PHP packages are installed (RedHat).] ********* 
skipping: [*********]

TASK: [geerlingguy.php | Ensure PHP packages are installed (Debian).] ********* 
ok: [*********] => (item=php5,libapache2-mod-fastcgi,php5-mcrypt,php5-cli,php5-common,php5-curl,php5-dev,php5-fpm,php5-gd,php5-imagick,php5-xdebug)

TASK: [geerlingguy.php | Place PHP configuration file in place.] ************** 
failed: [*********] => {"failed": true}
msg: Destination directory /etc/php5/apache2 does not exist

FATAL: all hosts have already failed -- aborting

**Comment by geerlingguy** [comment]
Two questions:

  1. Do you have `php_conf_path` set to `""` in your variables somewhere? If it's explicitly set and empty, then the 'Ensure configuration directories exist.' task won't run to create it.
  2. Are you sure you're running the latest version of this role on your Ansible host? Check by updating the role with `ansible-galaxy install --force geerlingguy.php`.

**Comment by zeroespace** [comment]
Hello Jeff, Thank you for the reply.
php_conf_path  was not set but I think it was a version issue because it is running the configuration directories check now.

Thanks a lot

**Comment by geerlingguy** [comment]
Ah, could be. Glad you could get it working!
