### ISSUE TITLE
Fails in check mode

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-php#42]
`error while evaluating conditional: php_version.stdout.split('.')[0] == '5' and php_version.stdout.split('.')[1] < '5'` in tasks/main.yml: 41

You could add an 'always_run' to the task registering php_version but then that would fail if no PHP has been installed yet wouldn't it?

Perhaps also add a `- "ansible-playbook -i tests/inventory tests/$SITE --check"` to your travis tests?

**Comment by geerlingguy** [comment]
I was about to mention that I *do* run the playbook twice in travis... then realized that you were mentioning check mode.

I think the best solution is to simply use `always_run` to `yes` for the registration task.

For those who don't yet have PHP installed, this will cause a failure... but that's kind of the point, in a sense—`--check` is more often used for verifying current configuration, and when someone is using it to do a dry-run prior to running a playbook the first time, there are some things that aren't that easy to `--check` without the playbook having been run once at least.
