### ISSUE TITLE
Make the role compatible with Rocky linux

### ISSUE THREAD

**Issue by SonOfWinter** [geerlingguy/ansible-role-php#429]
The role does not currently work with systems from the Rocky Linux family.

**Comment by racke** [comment]
Which version of ansible-core do you use?

**Comment by SonOfWinter** [comment]
ansible 2.10.6
python 3.9.18

Is it possible that the version I'm using doesn't know Rocky linux?

**Comment by racke** [comment]
Yes, that is really likely.  Ansible is EOL since 23 May 2022.

**Comment by SonOfWinter** [comment]
I updated it and now everything works correctly.
Thank you for your help
