### ISSUE TITLE
php5-mcrypt on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by bennoislost** [geerlingguy/ansible-role-php#50]
Hello

When installing `php5-mcrypt` via apt on Ubuntu 14.04 it is not enabled by default like it is on 12.04 :(

Once installed it can be enabled with the following commands

```
sudo php5enmod mcrypt
sudo service apache2 restart
```

Im not sure if this effects any other distro's currently.

I can have a look at submitting a PR but i'm not sure on the consequences for other distro's and the best method to update the role.

Cheers, Ben.

**Comment by MauroNigrele** [comment]
This is an ubuntu distro well known bug you must link mycrypt.ini

- name: Php | Fix Php5-Fpm mcrypt Extension
  file:
    src=/etc/php5/mods-available/mcrypt.ini
    dest=/etc/php5/fpm/conf.d/20-mcrypt.ini
    state=link
    mode=644

- name: Php | Fix Php5-CLI mcrypt Extension
  file:
    src=/etc/php5/mods-available/mcrypt.ini
    dest=/etc/php5/cli/conf.d/20-mcrypt.ini
    state=link
    mode=644

i have a role just to do this

**Comment by ssachtleben** [comment]
@MauroNigrele is the role public? I have the same issue now :smile:

**Comment by MauroNigrele** [comment]
@ssachtleben no, we have all roles in a common private repo on bitbucket, because our (company) roles are just 'stack-like' roles (magento/wordpress/etc), but i can make a copy here if you still need it, in sake of true, if i remember well it's just a task inside a role just for simplicity.

**Comment by geerlingguy** [comment]
I'm going to close this issue, and point people to https://github.com/ssachtleben/ansible-role-apache-mcrypt if they need to make sure the mcrypt extension is readily available in their PHP installation. Thanks!
