### ISSUE TITLE
php.ini is not applied in certain situations on Ubuntu

### ISSUE THREAD

**Issue by ArtemProkopenko** [geerlingguy/ansible-role-php#53]
Hello, I'm not sure whether it's a bug.
Role creates a configuration in /etc/php5/php.ini, but PHP use another files:
/etc/php5/cli/php.ini - for cli, and
/etc/php5/fpm/php.ini - for php-fpm

This forces to write additional code
```
    - name: Copy php.ini to php5/cli
      command: cp /etc/php5/php.ini /etc/php5/cli/php.ini

    - name: Copy php.ini to php5/fpm
      command: cp /etc/php5/php.ini /etc/php5/fpm/php.ini
      notify: restart php-fpm
```

**Comment by mikegleasonjr** [comment]
:+1: 

I'm also using php-fpm and experiencing the same bug.. my `phpinfo()` says...

```
Loaded Configuration File	/etc/php5/fpm/php.ini
```
But the template modified is:

```
/etc/php5/php.ini
```

Thank you for your modules, I'm using 3-4 of them :)

**Comment by maschmann** [comment]
@geerlingguy I see two options here: Changing the distributed default php.ini makes it harder to update later on, since e.g. apt will ask if the ini should be changed and what strategy it should take.
But it would be an easy fix ;-)
The other option would be either a douplicate or a minimal config template for cli, provisioned as e.g. 99-custom.php.ini into the autoload init.d folders of the respective cli/fpm folders.
This will double the config overhead - but in my opinion it's the preferable option, since this is minimally invasive and maximally customizable.

**Comment by teadur** [comment]
not sure if its cleanest method but made pull request what seems to resolve it for atleast php-fpm
https://github.com/geerlingguy/ansible-role-php/pull/60

**Comment by geerlingguy** [comment]
We can work on this a little more through #60 but regardless, the main thing I need to research (unless someone else wants to do it for me ;) is whether the actual path to the FPM config is the same between Debian-flavors and RHEL-flavors (relative to `php_conf_path`, of course).

**Comment by geerlingguy** [comment]
Also, looks like the role currently handles Apache2 on Ubuntu, FPM on at least certain Ubuntu versions, and FPM and CLI on RHEL correctly. Looks like it's mostly Ubuntu's crazy pathing that's throwing the role for a loop. Will do a bit more investigation on this once I get finished with #64

**Comment by geerlingguy** [comment]
Debian/Ubuntu--

**Comment by oxyc** [comment]
I've set up a test suite to run all possible permutations locally (20 docker instances). Unfortunately it will take ages to complete as my internet connection sucks. https://github.com/oxyc/ansible-role-php/commit/0cd2f601dd3f754cfa57a9497366f16534c800a0

@geerlingguy if you have time, do you mind glancing at the test playbooks to see if they look correct? Ive really never used anything but `apache` on ubuntu with drupal vm :P

**Comment by geerlingguy** [comment]
@oxyc - Looks good to me. I like how you chose 191MB... so close to 192, makes my OCD tendencies twitch :)

And we gotta get you a better connection! Wish I could beam a few Mbps your way.

**Comment by maschmann** [comment]
maybe we can leverage docker containers on travis.ci?

**Comment by oxyc** [comment]
Unfortunately you dont have access to sudo on the container-based infrastructure. Also I'm not sure you can choose the base image :/

**Comment by geerlingguy** [comment]
@oxyc is correct on both accounts :(

But you could abuse the heck out of a pull request to get Travis to test using your own docker configs :D
