### ISSUE TITLE
Default naming of opcache.ini symlinks

### ISSUE THREAD

**Issue by iAugur** [geerlingguy/ansible-role-php#57]
The OS default names of the opcache.ini sysmlinks (apache and cli) are:
RedHat: 10-opcache.ini
Debian: 20-opcache.ini
The Ansible role vars for the OS family are:
Redhat: opcache.ini
Debian: 05-opcache.ini
If PHP gets updated (e.g. security update)  the default symlinks will be created and you will have two (both the default and the ansible created ones).
This causes errors when Apache restarts and tries to load the module twice.
I think the best solution is to use the OS default names (unless the oredr of inclusion is important?)
This can be overridden in plays using this role using:
php_opcache_conf_filename
But may be worth updating the defaults in the vars?

**Comment by geerlingguy** [comment]
Working on this now...

**Comment by geerlingguy** [comment]
It looks like Debian should actually be 05-opcache.ini, as that's the default filename mentioned for every tutorial I could find, and it's what's installed when installing PHP/Apache out of the box in Ubuntu... could it be different for Debian 8 or some other variation?

**Comment by iAugur** [comment]
Apologies for the Debian filename - that was earlier versions of PHP/opcache (which no one should really be using anymore).
It was the RedHat one that caught me out, so that still stands and worth noting as a gotcha when creating such files when they already exist (possible with a different name). I note your change also for the apc ini name change.
I have done further testing and Debian 8 it is 05-opcache.ini
I will test further and report back if any OS / PHP version combinations contradict this.

**Comment by geerlingguy** [comment]
@iAugur - No problem, thanks for following up! Please open a new issue with your numbering findings. Unfortunately, I can't find any definitive resource with numbering standards for either of the main platforms, so I'll just have to spin up a bunch of instances and see what the defaults are.
