### ISSUE TITLE
PHP session errors, possible misconfiguration?

### ISSUE THREAD

**Issue by joshrickert** [geerlingguy/ansible-role-php#63]
I'm working with a fork of the Drupal-VM repo, and PimpMyLog is throwing the following error:

```
PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /usr/share/php/pimpmylog/inc/classes/Session.php on line 45
```

From what I can tell, this is because PHP's built-in session garbage collector is kicking in, when it should actually be disabled (on Ubuntu) because there is a cron job to take care of that.

I found a [recommended fix](http://vvv.tobiassjosten.net/php/php-session-garbage-collection/) which involves setting `session.gc_probability = 0` in php.ini, but it looks like this role doesn't give a lot of flexibility to update the template. I could replace the whole PHP.ini file per the documentation, but that seems like overkill for what might be just a misconfiguration.

My config overrides, in case it helps for debugging:
```
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_enable_apc: 0
php_opcache_enable: 0
php_realpath_cache_size: "16K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
```

**Comment by geerlingguy** [comment]
You now have full control over the main session gc settings as a result of https://github.com/geerlingguy/ansible-role-php/pull/79 :)

I'll have a new tagged release of this role on Galaxy very soon.
