### ISSUE TITLE
Doc improvment - APC is dead, long live the OpCache

### ISSUE THREAD

**Issue by remicollet** [geerlingguy/ansible-role-php#69]
Doc refers to "APC"

This is dead, and opcache should be prefered (when available).

But people using PHP >= 5.5 main need APC, only for user data cache. In this case APCu (or apcu_bc with PHP 7) is available.

Perhaps the documentation shoudl (try) to explain this...

In all case, everything which make people away from APC (original) is good ;)

**Comment by geerlingguy** [comment]
True... when I originally wrote this role, PHP 5.5 was bleeding edge, so opcache was still a 'new' thing and APC was the stable opcache mechanism.

It may be time for me to switch all the docs and examples to 5.6 preferred.

**Comment by geerlingguy** [comment]
Fixed in the above commit!
