### ISSUE TITLE
php5-fpm.sock is missing

### ISSUE THREAD

**Issue by gregorskii** [geerlingguy/ansible-role-php#73]
Hi,

The recent updates to this role seem to have removed the php5-fpm.sock file from /var/run.

We were using this file in our nginx site config:

```
location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
```

Was this intentional? Am I setting up nginx incorrectly?

It is resulting in this error:

```
2016/01/22 18:57:43 [crit] 6648#0: *9 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: <IP>, server: <HOST>, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "<HOST>"
```

Thanks.

**Comment by geerlingguy** [comment]
The recent updates added some new `php_fpm_*` variables, and one of the new defaults is:

    php_fpm_listen: "127.0.0.1:9000"

You will need to overrided this and set it to `"/var/run/php5-fpm.sock"` to default it back to what (I think) Ubuntu's default listen config was.

(See: https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml#L10)
