### ISSUE TITLE
Set always_populate_raw_post_data to -1 by default

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/ansible-role-php#74]
On a default provision you can't enable the REST module in D8 because ```always_populate_raw_post_data``` should be set to ```-1``` in php.ini

It'd be nice if this was set by default.

**Comment by geerlingguy** [comment]
Hmm... this configuration variable is removed in 7.0.0, so I might not want to add it in (see: http://php.net/manual/en/ini.core.php). Is there any other way you can set that var at runtime, in settings.php, or elsewhere?

**Comment by geerlingguy** [comment]
This was fixed in #81
