### ISSUE TITLE
Wrong variable "php_installed_versionl"

### ISSUE THREAD

**Issue by Smurv** [geerlingguy/ansible-role-php#76]
Hi,

in file " ansible-role-php/tasks/main.yml" on line 48 there is:

`shell: '{{ php_executable }} -r "echo php_installed_version;"'`

but "php_installed_version" is not PHP variable. It should be "PHP_VERSION":

`shell: '{{ php_executable }} -r "echo PHP_VERSION;"'`

Sorry, I'm new to github and don't know, how to pull code :-(

Than

**Comment by geerlingguy** [comment]
Thanks for noting this!
