### ISSUE TITLE
Pear and APC should not be installed for PHP 7

### ISSUE THREAD

**Issue by achton** [geerlingguy/ansible-role-php#95]
When building DrupalVM with PHP 7, I got an error in the **Ensure PHP packages are installed.** task from this role.

It is due to the `vars/Debian.yml` file containing the `php-pear` and `php-apc` packages, and I could get the machine to build by commenting out those packages.

I am on Ubuntu and Ansible 2.x, Vagrant 1.8 and Virtualbox 5. 
Is there something I have overlooked?

**Comment by thom8** [comment]
@achton you'll need to override the `php_packages` var with PHP7 packages -- http://docs.drupalvm.com/en/latest/other/php-7/

**Comment by achton** [comment]
@thom8 Thanks, I don't know how I did not see that.
