### ISSUE TITLE
php-fpm pool www.conf will be created even php-fpm isn't installed

### ISSUE THREAD

**Issue by StefanKlatt** [geerlingguy/ansible-role-php#98]
Hi,

php-fpm pool www.conf will be created even php-fpm isn't installed.

What about extending the the last task "# Configure PHP-FPM." with: 

 when: php_enable_php_fpm

?

Regards

Stefan

**Comment by acie** [comment]
Hi,

I also got the same issue. Even on my defaults/main.yml the **php_enable_php_fpm: false**. PHP-FPM is still running.

Any advice?

Thanks.

**Comment by geerlingguy** [comment]
True... the `when` would need to be added on [this task](https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/configure-fpm.yml#L36), `Ensure the default pool exists.`. I may do this... no need to add the config if it's not being used.

**Comment by geerlingguy** [comment]
This was fixed in the above commit. Thanks @FlxPeters !
